services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"  # 외부에서 접근할 포트
    volumes:
      - ./src:/home/Jamiron_BE/src   # 로컬 src를 컨테이너 src에 마운트
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: tempPass!
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  redis_data: